services:
  - type: web
    name: playverse-backend
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: node dist/app.js
    envVars:
      - key: NODE_VERSION
        value: 20